### ISSUE TITLE
FR: Extract meeting URL from event description or location

### ISSUE THREAD

**Issue by livejamie** [muness/obsidian-ics#14]
Would be killer to be able to display other information from the .ICS file like location to get zoom links/meeting rooms/etc.

**Comment by geosmina** [comment]
> Would be killer to be able to display other information from the .ICS file like location to get zoom links/meeting rooms/etc.

Or the description of the event as a list one tabulation more inside the event. It would be perfect!

**Comment by muness** [comment]
I'd love to pull this off, but it may be hard.

From what I've seen different providers are storing these details in the description field and doing so inconsistently. I'll try for something common like looking up how Google Meeting URLs are stored by Google Calendar and see if I come up with a rule to extract those.

**Comment by muness** [comment]
Looks like Google uses a VEVENT field `GOOGLE-CONFERENCE`. Let's see if there's similar fields from others...
