### ISSUE TITLE
Can this work without daily notes?

### ISSUE THREAD

**Issue by dylan-k** [muness/obsidian-ics#16]
I don't use daily notes, preferring instead to make notes about ideas, but I do have a kind of "dashboard" note where this could be useful. Is it required to only work on a daily note? Could there be an alternative?

**Comment by muness** [comment]
For now I focused on daily notes since I have to pull events for a specific time period. How would you like to specify the period you want events for, @dylan-k ?

**Comment by accelyte** [comment]
I'm also in a similar spot. Following on @dylan-k's idea, my suggestion is to add two options:
1. Enable auto refreshing: pull the current day's events (using system time?) into the template note, and refresh/update an auto-generated note
2. Point to the template note

This can even work in conjunction with Day Planner, which has `Command mode` to update the timeline according to a specific note.

**Comment by barolo** [comment]
I would love to see integration with Day Planner, just auto-pulling a range of events and putting it for display in the panel.

**Comment by dylan-k** [comment]
> How would you like to specify the period you want events for?

@muness by day, week, or month, I suppose. The default functionality would be fine, but from any note.

**Comment by muness** [comment]
Closing this as using Core Template, Dataview or Templater would allow for these kinds of interactions per day. For more than one day, I'd have to update the event finding code to support a date range. I don't think that would be hard: please open a new issue for that if you need it.
