### ISSUE TITLE
FR: Add ability to include calendar list in daily notes template

### ISSUE THREAD

**Issue by amichuda** [muness/obsidian-ics#24]
Hi! Is it possible to make the calendar list appear as part of a template? Something similar to an `obsidian-tasks` template where it generates the calendar for that day when you create a daily note automatically?

**Comment by kmaustral** [comment]
As an interim, I've tried to make a button for this plug-in as part of my Daily Notes template. But it seems to send the feed to the top of the page, rather than where the button is. I'm curious if anyone else has had success.

**Comment by kmaustral** [comment]
Thanks. Yes, that works. I'll raise the issue with Buttons.

**Comment by pcause** [comment]
I looked at the code and I can use javascript:

`$= let x= await this.app.plugins.plugins['ics'].getEvents();return x;`

to get the events, but can't figure out how to call the function that is called by obsidian for the command, which adds the reformatting.  Will see if I can add that to my snippet.  BUT, if the author can make a function that can be directly called or tell me how to access the registered callback, we can add it to the README and I am sure a lot of folks will copy/paste it

**Comment by pcause** [comment]
i Looked and getEvents is only called from the callback.  you could move the code in the callback into getEvents and have it return mdArray and then the callback would call events and use the results for the editor.replace call.  If you think there is a need to return the event object array, you could add an argument to getEvents to specify whether to return the events as objects or as the array of strings

**Comment by muness** [comment]
Since I documented how to use Templater + Dataview to do this, closing this issue.

**Comment by kmaustral** [comment]
Can you say what the script is that you include in the documentation?
Should it be prefaced by `<%` or `dataviewjs`?

Thanks.

**Comment by muness** [comment]
When I try the code:

![image](https://github.com/muness/obsidian-ics/assets/931/2bf72638-1f7d-41a9-a22a-b5d01ccd1b5b)

I get back the events rendered:

<img width="503" alt="image" src="https://github.com/muness/obsidian-ics/assets/931/6781fb4c-0b65-46e7-8343-d2eefbcff263">

**Comment by muness** [comment]
@kmaustral I also added [documentation](https://github.com/muness/obsidian-ics/blob/master/README.md#templater) for using Templater. Hope one of those works for your use case.
