### ISSUE TITLE
Feature Request: Add Break events at the end of calendar events if another calendar event is not starting at that time.

### ISSUE THREAD

**Issue by erikshelley** [muness/obsidian-ics#34]
If I have a one hour event then a four hour break before the next event starts I don't want it to look like my first event is five hours long.

I cloned the repository and implemented this change but I'm not sure how to share my code. I've never contributed to someone else's project on GitHub before. Let me know if you're interested in my implementation.

**Comment by Dragonslayersakata** [comment]
This would be a great addition!

**Comment by muness** [comment]
With the changes to https://github.com/ivan-lednev/obsidian-day-planner and the addition of the end time per object I am closing this. If you still want it, please reopen the issue with more details about the scenario you want it for and what kind of break events you'd expect and how you'd want it configured.
