### ISSUE TITLE
Calendar events are missing

### ISSUE THREAD

**Issue by pauby** [muness/obsidian-ics#36]
When I import calendar events, some of them are always missing. It's not always the same ones. So for example, a recurring meeting that is there every day will appear yesterday, but not appear today. Running it again results in the same results.

The meetings do appear in the ICS file that is downloaded from Google Calendar with the correct date and time.

The meetings I have _noticed_ are recurring meetings. But there may be others (which I'm now keeping an eye on).

**Comment by muness** [comment]
@pauby - I've noticed this too but haven't been able to debug it (will update the README to say that I don't get to use this at work any more making investment hard).

The only thought I have is that the recurring logic (https://github.com/muness/obsidian-ics/blob/master/src/icalUtils.ts#L17) is at fault. I've debugged other similar issues using the inspector and simple debugging calendars but haven't been able to home in on this one yet.

**Comment by tpulha** [comment]
Recurrent events still missing.

**Comment by muness** [comment]
Thanks for letting me @tpulha .

I am using the plugin again, so will take a look as it affected a recurring meeting I had last week.

**Comment by muness** [comment]
The node-ical library has some updated instructions on RRule detection https://github.com/jens-maus/node-ical#recurrence-rule-rrule . I'll give this to see if this fixes the issue. 🤞

**Comment by muness** [comment]
I think this is now fixed with https://github.com/muness/obsidian-ics/pull/47 . Please reopen if you're still seeing the issue.
