### ISSUE TITLE
Feature request: Command to import events from one specific calendar

### ISSUE THREAD

**Issue by machado-t** [muness/obsidian-ics#41]
As of now, only importing events from all defined calendars is possible.

**Comment by tpulha** [comment]
A command for each calendar could be more useful.

**Comment by muness** [comment]
Hi @machado-t , I suggest that for this kind of customization, you should try using Templater or Dataview. Use `app.plugins.getPlugin('ics').getEvents()` and then display the output any way you want. The `icsName` contains the calendar that the event belongs to.
