### ISSUE TITLE
Feat : Related to adding output format functionality

### ISSUE THREAD

**Issue by GoBeromsu** [muness/obsidian-ics#54]
I'm using the plug-in very well Thank you.
I don't want to print out the name of the ics

Furthermore, what do you think of allowing the output format to be customized by the user?
- The description of the Google calendar, etc

**Comment by Dragonslayersakata** [comment]
I think the ability to customize the output would be a great addition. I would like to have the events added under a specific header so that the Day Planner add-on can track the events.

**Comment by muness** [comment]
@GoBeromsu - I am going to close this given that I've merged #55 . Thank you!
