### ISSUE TITLE
FR: Submit to community for easier install

### ISSUE THREAD

**Issue by muness** [muness/obsidian-ics#6]

**Comment by livejamie** [comment]
This would be convenient

**Comment by rzfzr** [comment]
I'm organizing the tasks from this [link](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list) 

Preparing your repository
[Publish an initial version](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+release+a+new+version+of+your+plugin) of your plugin.
Make sure you have a README.md file in the root of your repo, clearly describing the plugins purpose and providing clear usage instructions.
Add a license to your repository. You can use [Choose a License](https://choosealicense.com/) if you don't know which one to pick.
Check that your manifest.json is at the root of your repo.

**Comment by rzfzr** [comment]
I'm organizing the tasks from this [link](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list) as some of them should be done by the owner. From what I can see the only thing lacking is the license.

- [ ] Add a license to your repository. You can use [Choose a License](https://choosealicense.com/) if you don't know which one to pick.
(GH has also a helping [template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that helps you choose)

After adding the license, @muness could fork [this repo](https://github.com/obsidianmd/obsidian-releases#community-plugins)? I'll set it up so that you can just do the final PR.

**Comment by muness** [comment]
Thanks @rzfzr ! I added a license to the plugin.

**Comment by muness** [comment]
@rzfzr fork of https://github.com/obsidianmd/obsidian-releases#community-plugins created at https://github.com/muness/obsidian-releases

**Comment by muness** [comment]
Submitted a PR to obsidian-releases: https://github.com/obsidianmd/obsidian-releases/pull/965 . 

Build broke when 0.14.8 shipped (npm install was failing) fixing that now...

**Comment by muness** [comment]
Github Actions Workflow continues to stall during npm install https://github.com/muness/obsidian-ics/runs/6536940288?check_suite_focus=true . I'll take a look later to see if it's something on my end or an infra issue in GH Actions.

**Comment by rzfzr** [comment]
Great stuff! I'll do my part later this week

**Comment by muness** [comment]
Build fixed. I'll test the plugin zip tomorrow one more time given the dependency changes then promote the PR from draft once I confirm 0.9.12 works correctly.

**Comment by muness** [comment]
Tested the plugin and fixed https://github.com/obsidianmd/obsidian-releases/pull/965/. PR is now ready for review.

**Comment by muness** [comment]
In my last attempt I got [feedback ](https://github.com/obsidianmd/obsidian-releases/pull/965#issuecomment-1143704584) to address:

- [ ] remove the console.log
- [ ] You should add some error handling for the request() function
- [ ] while there's no rule against it, I suggest removing the default hotkey and maybe mentioning a recommended hotkey in your README.
- [ ] you should use window.moment instead to avoid including your own instance of Moment.js. Obsidian also has the window.moment instance localized based on the user settings, so it's best to avoid this.
- [ ] Isn't dates an array? You shouldn't use for ... in here. That is for iterating over objects. You should be using for ... of

**Comment by muness** [comment]
New [feedback](https://github.com/obsidianmd/obsidian-releases/pull/2208#issuecomment-1655992604):

- [ ] Avoid including sentences like "This is a plugin for Obsidian" in your description.

- [ ] re [node-ical](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/package.json#L16): This library is only available from a nodeJS runtime, which means that this will throw errors on Mobile (that's a problem since you have isDesktopOnly marked as false in your manifest.json file, or am I missing something?
- [ ] You should use a editor callback [here](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/main.ts#L85-L95), that way the command will only be available if there is a editor available: https://docs.obsidian.md/Plugins/User+interface/Commands#Editor+commands

- [ ] Would be nicer to use import {moment} from "obsidian"; [here](https://github.com/muness/obsidian-ics/blob/5b0847186cf9a040c3e49421d69fb007198151ae/src/icalUtils.ts#L21).
- [ ] [Only use headings under settings if you have more than one section.](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
- [ ] [Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)
