### ISSUE TITLE
Allow setting for custom event prefix and suffix

### ISSUE THREAD

**Issue by huzaifahj** [muness/obsidian-ics#77]
Generalise the setting for what appears before/after the event time, so we can have output like:
`- 08:00 Breakfast`
`- [ ] 08:00 Breakfast`
`08:00 Breakfast`
`**08:00 Breakfast**`
`## 08:00 Breakfast`

**Comment by huzaifahj** [comment]
I was able to do this with the Templater plugin:

```
<%
(async () => {
  var events = await app.plugins.getPlugin('ics').getEvents();
  var lines = [];
  events.forEach((e) => {
	lines.push(`${e.time} ${e.summary}`)
  })
  return lines.join("\n")}
)()
%>
```

But would be nice if the functionality was built-in

**Comment by muness** [comment]
At least for now, I'd prefer to keep such customizations to Templater templates. I worry that the basic usage and settings will get too complicated otherwise.
