### ISSUE TITLE
BUG: Daylight time shift led to incorrect hours

### ISSUE THREAD

**Issue by muness** [muness/obsidian-ics#79]
With the time change, some of my event times are incorrect.

**Comment by kfitz** [comment]
Mine too! And I'm not sure if you saw my comment on the prior closed issue, but that daily recurring event is now CORRECT! The first day of the event is in standard time, so it's correct now and incorrect during daylight saving time.

**Comment by muness** [comment]
Thanks for confirming, @kfitz . I hate timezones...

Maybe I should invest in a debug mode that gives us more details (about the original series for recurring events?) in the console that we can include in bug reports.

**Comment by muness** [comment]
On debugging, I believe the issue is that I am currently using UTC offsets to calculate the event's new time. This correctly means that a 10am EDT (-0400) becomes 9am EST (-0500).

Fixing to not go back to UTC offsets.

**Comment by muness** [comment]
Please reopen if the issue(s) persist!

**Comment by muness** [comment]
> Mine too! And I'm not sure if you saw my comment on the prior closed issue, but that daily recurring event is now CORRECT! The first day of the event is in standard time, so it's correct now and incorrect during daylight saving time.

This was the key. I am guessing this even was in EST. When we flipped back to EST, it became correct again. The new code should no longer flip back and forth, keeping events constant when DST changes.
