### ISSUE TITLE
FR: make time format compatible with Dataview Metadata / FullCalendar Daily Note Syntax

### ISSUE THREAD

**Issue by pcause** [muness/obsidian-ics#81]
I want to be able to enter some surrounding text to the time that you create when you import the event.  For example, I'd like to have 2 fields in the form

start format - [[ startTime:: HH:mm ]]
end format - [[ endTime:: HH:mm ]]

and have it create an event like:

- [ ] [[ startTime:: 09:00]]  [[ endTime:: 10:00 ]] title location

you basically look for the time spec and only replace that and pass through the rest.  Would also be useful to have length used instead of end time.  

Thanks for the plugin!

**Comment by muness** [comment]
@pcause - In an attempt to keep the settings UI from getting too complicated, I've encouraged people who want more customization to use Templater, per the README [example](https://github.com/muness/obsidian-ics#templater).

What do you think?

**Comment by pcause** [comment]
I understand the desire.  I can use and modify the script but I suspect a lot of users can't.  

Perhaps an option that say to show times in dataview format.  If the user doesn't know what this is they won't use it and stick with the simple format you have. Since dataview is a hugely popular output this will help lots of people who use dataview for their tasks displays.  

If you add, it would put [[ startTime: HH:mm ]] and [[ length:: HH:mm ]] as the output.   And if you put the start/length at the beginning of the line the sort by time is easy for folks using things like the tasks plugin.

**Comment by muness** [comment]
@pcause , why the wiki brackets `[[` around `[[ startTime: HH:mm ]]`` ? I don't use Dataview so am not following how the usage plays out. Maybe you share an example of how you're using it, and I'll use that as a spec / documentation reference? 🙇‍♂️

**Comment by muness** [comment]
Looking at the [Metadata on Tasks and Lists docs](https://blacksmithgu.github.io/obsidian-dataview/annotation/metadata-tasks/), I think we want:
- [startTime:: <start time>]
- [endTime:: <endTime>]

Looking at the forum discussion [Custom Full Calendar with DataView](https://forum.obsidian.md/t/custom-full-calendar-with-dataview/34133) and [Full Calendar's docs on DataView integration](https://davish.github.io/obsidian-full-calendar/advanced/dataview/) it seems like it may further be worth making the start/end keys either configurable, maybe defaulting to `start` and `end`.

**Comment by muness** [comment]
That format above should also work with [Full Calendar + Daily Notes too](https://davish.github.io/obsidian-full-calendar/calendars/dailynote/) though in this example they just use `startTime` and `endTime`.

**Comment by muness** [comment]
Released as 1.4.0, thanks @pcause ! Please let me know if you see issues / opportunities to make this better.
