### ISSUE TITLE
templater and query using dataview format isn't showing dataview format

### ISSUE THREAD

**Issue by pcause** [muness/obsidian-ics#83]
I used the templater example and modified it to also show endTime:

`%*
var events = await app.plugins.getPlugin('ics').getEvents(moment(tp.file.title,'YYYY-MM-DD'));
events.sort((a,b) => a.utime - b.utime).forEach((e) => {
  tR+=`- [ ] ${e.time} ${e.endTime} ${e.summary} ${e.location? e.location : ''}\n`
})
%>`

but I get the following:

- [ ] 00:00 00:00 Veterans Day (Observed) United States
- [ ] 06:30 07:25 email handling 

if I run the import events command manually I get:

- [ ] [startTime:: 00:00] [endTime:: 00:00] Veterans Day (Observed) United States
- [ ] [startTime:: 06:30] [endTime:: 07:25] email handling

I can, of course change the javascript, but think that if I enable dataview format e.time and e.endTime should be returned in dataview format.

**Comment by muness** [comment]
If someone is already using a template, I'll leave it up to them to format as they see fit. Thanks for the suggestion.
