### ISSUE TITLE
BUG: Checkbox/bullet setting stored globally, not per calendar

### ISSUE THREAD

**Issue by aventuraviper** [muness/obsidian-ics#87]
Hi,

Thank you for this great plugin. You recently added checkbox or bullet option per calendar (if I have undestood https://github.com/muness/obsidian-ics/issues/67) correctly. However when enabling checkbox on one subscription it changed it for all and vice versa.

Kind regards
Gavin

Obsidian: 1.4.16
Plugin: 1.4.0

**Comment by muness** [comment]
Thanks for the bug report @aventuraviper , this is supposed to be per calendar, but I may have messed up the settings modal code. I'll try to reproduce the issue.

**Comment by muness** [comment]
Hi @aventuraviper - I haven't been able to reproduce. In my Vault I have 4 calendars and when I change between checkbox and bullet the change only affects that calendar's entries as expected.

Can you try again and share the steps that show the issue?

**Comment by muness** [comment]
Can't reproduce
