### ISSUE TITLE
Cannot activate ICS

### ISSUE THREAD

**Issue by achuwilson** [muness/obsidian-ics#9]
`Plugin failure: ics-plugin Error: ENOENT: no such file or directory, open '/home/acw/works/obsidian/acw-thoughts/.obsidian/plugins/obsidian-ics/main.js`

**Comment by flatlines** [comment]
I have the same issue. Obsidian returns "failed to load plugin" on Windows.

**Comment by muness** [comment]
The release zip file (the one with the -[version]) includes a compiled `main.js`. https://github.com/muness/obsidian-ics/commit/067f36921c8923c3ed07ca6d76ae35eae1d903fc added that clarification, and #6 should obviate the need for manual installs altogether so closing this.

Let me know if you still have trouble with the plugin not loading!
